/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedVehiclesRouteImport } from './routes/_authenticated/vehicles'
import { Route as AuthenticatedTripsRouteImport } from './routes/_authenticated/trips'
import { Route as AuthenticatedSubscriptionsRouteImport } from './routes/_authenticated/subscriptions'
import { Route as AuthenticatedStudentsRouteImport } from './routes/_authenticated/students'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedSchoolsRouteImport } from './routes/_authenticated/schools'
import { Route as AuthenticatedSchoolSettingsRouteImport } from './routes/_authenticated/school-settings'
import { Route as AuthenticatedSchoolAdminsRouteImport } from './routes/_authenticated/school-admins'
import { Route as AuthenticatedRoutesRouteImport } from './routes/_authenticated/routes'
import { Route as AuthenticatedReportsRouteImport } from './routes/_authenticated/reports'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated/profile'
import { Route as AuthenticatedPlansRouteImport } from './routes/_authenticated/plans'
import { Route as AuthenticatedParentsRouteImport } from './routes/_authenticated/parents'
import { Route as AuthenticatedNotificationsRouteImport } from './routes/_authenticated/notifications'
import { Route as AuthenticatedMyChildrenRouteImport } from './routes/_authenticated/my-children'
import { Route as AuthenticatedDriversRouteImport } from './routes/_authenticated/drivers'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedStudentsIndexRouteImport } from './routes/_authenticated/students.index'
import { Route as AuthenticatedSchoolsIndexRouteImport } from './routes/_authenticated/schools.index'
import { Route as AuthenticatedDriversIndexRouteImport } from './routes/_authenticated/drivers.index'
import { Route as AuthenticatedStudentsStudentIdRouteImport } from './routes/_authenticated/students.$studentId'
import { Route as AuthenticatedSchoolsSchoolIdRouteImport } from './routes/_authenticated/schools.$schoolId'

const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedVehiclesRoute = AuthenticatedVehiclesRouteImport.update({
  id: '/vehicles',
  path: '/vehicles',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTripsRoute = AuthenticatedTripsRouteImport.update({
  id: '/trips',
  path: '/trips',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSubscriptionsRoute =
  AuthenticatedSubscriptionsRouteImport.update({
    id: '/subscriptions',
    path: '/subscriptions',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedStudentsRoute = AuthenticatedStudentsRouteImport.update({
  id: '/students',
  path: '/students',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSchoolsRoute = AuthenticatedSchoolsRouteImport.update({
  id: '/schools',
  path: '/schools',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSchoolSettingsRoute =
  AuthenticatedSchoolSettingsRouteImport.update({
    id: '/school-settings',
    path: '/school-settings',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSchoolAdminsRoute =
  AuthenticatedSchoolAdminsRouteImport.update({
    id: '/school-admins',
    path: '/school-admins',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedRoutesRoute = AuthenticatedRoutesRouteImport.update({
  id: '/routes',
  path: '/routes',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedReportsRoute = AuthenticatedReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPlansRoute = AuthenticatedPlansRouteImport.update({
  id: '/plans',
  path: '/plans',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedParentsRoute = AuthenticatedParentsRouteImport.update({
  id: '/parents',
  path: '/parents',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedNotificationsRoute =
  AuthenticatedNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMyChildrenRoute = AuthenticatedMyChildrenRouteImport.update({
  id: '/my-children',
  path: '/my-children',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDriversRoute = AuthenticatedDriversRouteImport.update({
  id: '/drivers',
  path: '/drivers',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedStudentsIndexRoute =
  AuthenticatedStudentsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedStudentsRoute,
  } as any)
const AuthenticatedSchoolsIndexRoute =
  AuthenticatedSchoolsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedSchoolsRoute,
  } as any)
const AuthenticatedDriversIndexRoute =
  AuthenticatedDriversIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedDriversRoute,
  } as any)
const AuthenticatedStudentsStudentIdRoute =
  AuthenticatedStudentsStudentIdRouteImport.update({
    id: '/$studentId',
    path: '/$studentId',
    getParentRoute: () => AuthenticatedStudentsRoute,
  } as any)
const AuthenticatedSchoolsSchoolIdRoute =
  AuthenticatedSchoolsSchoolIdRouteImport.update({
    id: '/$schoolId',
    path: '/$schoolId',
    getParentRoute: () => AuthenticatedSchoolsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/drivers': typeof AuthenticatedDriversRouteWithChildren
  '/my-children': typeof AuthenticatedMyChildrenRoute
  '/notifications': typeof AuthenticatedNotificationsRoute
  '/parents': typeof AuthenticatedParentsRoute
  '/plans': typeof AuthenticatedPlansRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/reports': typeof AuthenticatedReportsRoute
  '/routes': typeof AuthenticatedRoutesRoute
  '/school-admins': typeof AuthenticatedSchoolAdminsRoute
  '/school-settings': typeof AuthenticatedSchoolSettingsRoute
  '/schools': typeof AuthenticatedSchoolsRouteWithChildren
  '/settings': typeof AuthenticatedSettingsRoute
  '/students': typeof AuthenticatedStudentsRouteWithChildren
  '/subscriptions': typeof AuthenticatedSubscriptionsRoute
  '/trips': typeof AuthenticatedTripsRoute
  '/vehicles': typeof AuthenticatedVehiclesRoute
  '/schools/$schoolId': typeof AuthenticatedSchoolsSchoolIdRoute
  '/students/$studentId': typeof AuthenticatedStudentsStudentIdRoute
  '/drivers/': typeof AuthenticatedDriversIndexRoute
  '/schools/': typeof AuthenticatedSchoolsIndexRoute
  '/students/': typeof AuthenticatedStudentsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/my-children': typeof AuthenticatedMyChildrenRoute
  '/notifications': typeof AuthenticatedNotificationsRoute
  '/parents': typeof AuthenticatedParentsRoute
  '/plans': typeof AuthenticatedPlansRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/reports': typeof AuthenticatedReportsRoute
  '/routes': typeof AuthenticatedRoutesRoute
  '/school-admins': typeof AuthenticatedSchoolAdminsRoute
  '/school-settings': typeof AuthenticatedSchoolSettingsRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/subscriptions': typeof AuthenticatedSubscriptionsRoute
  '/trips': typeof AuthenticatedTripsRoute
  '/vehicles': typeof AuthenticatedVehiclesRoute
  '/schools/$schoolId': typeof AuthenticatedSchoolsSchoolIdRoute
  '/students/$studentId': typeof AuthenticatedStudentsStudentIdRoute
  '/drivers': typeof AuthenticatedDriversIndexRoute
  '/schools': typeof AuthenticatedSchoolsIndexRoute
  '/students': typeof AuthenticatedStudentsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/drivers': typeof AuthenticatedDriversRouteWithChildren
  '/_authenticated/my-children': typeof AuthenticatedMyChildrenRoute
  '/_authenticated/notifications': typeof AuthenticatedNotificationsRoute
  '/_authenticated/parents': typeof AuthenticatedParentsRoute
  '/_authenticated/plans': typeof AuthenticatedPlansRoute
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/_authenticated/reports': typeof AuthenticatedReportsRoute
  '/_authenticated/routes': typeof AuthenticatedRoutesRoute
  '/_authenticated/school-admins': typeof AuthenticatedSchoolAdminsRoute
  '/_authenticated/school-settings': typeof AuthenticatedSchoolSettingsRoute
  '/_authenticated/schools': typeof AuthenticatedSchoolsRouteWithChildren
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/students': typeof AuthenticatedStudentsRouteWithChildren
  '/_authenticated/subscriptions': typeof AuthenticatedSubscriptionsRoute
  '/_authenticated/trips': typeof AuthenticatedTripsRoute
  '/_authenticated/vehicles': typeof AuthenticatedVehiclesRoute
  '/_authenticated/schools/$schoolId': typeof AuthenticatedSchoolsSchoolIdRoute
  '/_authenticated/students/$studentId': typeof AuthenticatedStudentsStudentIdRoute
  '/_authenticated/drivers/': typeof AuthenticatedDriversIndexRoute
  '/_authenticated/schools/': typeof AuthenticatedSchoolsIndexRoute
  '/_authenticated/students/': typeof AuthenticatedStudentsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/reset-password'
    | '/dashboard'
    | '/drivers'
    | '/my-children'
    | '/notifications'
    | '/parents'
    | '/plans'
    | '/profile'
    | '/reports'
    | '/routes'
    | '/school-admins'
    | '/school-settings'
    | '/schools'
    | '/settings'
    | '/students'
    | '/subscriptions'
    | '/trips'
    | '/vehicles'
    | '/schools/$schoolId'
    | '/students/$studentId'
    | '/drivers/'
    | '/schools/'
    | '/students/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/reset-password'
    | '/dashboard'
    | '/my-children'
    | '/notifications'
    | '/parents'
    | '/plans'
    | '/profile'
    | '/reports'
    | '/routes'
    | '/school-admins'
    | '/school-settings'
    | '/settings'
    | '/subscriptions'
    | '/trips'
    | '/vehicles'
    | '/schools/$schoolId'
    | '/students/$studentId'
    | '/drivers'
    | '/schools'
    | '/students'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/reset-password'
    | '/_authenticated/dashboard'
    | '/_authenticated/drivers'
    | '/_authenticated/my-children'
    | '/_authenticated/notifications'
    | '/_authenticated/parents'
    | '/_authenticated/plans'
    | '/_authenticated/profile'
    | '/_authenticated/reports'
    | '/_authenticated/routes'
    | '/_authenticated/school-admins'
    | '/_authenticated/school-settings'
    | '/_authenticated/schools'
    | '/_authenticated/settings'
    | '/_authenticated/students'
    | '/_authenticated/subscriptions'
    | '/_authenticated/trips'
    | '/_authenticated/vehicles'
    | '/_authenticated/schools/$schoolId'
    | '/_authenticated/students/$studentId'
    | '/_authenticated/drivers/'
    | '/_authenticated/schools/'
    | '/_authenticated/students/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/vehicles': {
      id: '/_authenticated/vehicles'
      path: '/vehicles'
      fullPath: '/vehicles'
      preLoaderRoute: typeof AuthenticatedVehiclesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/trips': {
      id: '/_authenticated/trips'
      path: '/trips'
      fullPath: '/trips'
      preLoaderRoute: typeof AuthenticatedTripsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/subscriptions': {
      id: '/_authenticated/subscriptions'
      path: '/subscriptions'
      fullPath: '/subscriptions'
      preLoaderRoute: typeof AuthenticatedSubscriptionsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/students': {
      id: '/_authenticated/students'
      path: '/students'
      fullPath: '/students'
      preLoaderRoute: typeof AuthenticatedStudentsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/schools': {
      id: '/_authenticated/schools'
      path: '/schools'
      fullPath: '/schools'
      preLoaderRoute: typeof AuthenticatedSchoolsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/school-settings': {
      id: '/_authenticated/school-settings'
      path: '/school-settings'
      fullPath: '/school-settings'
      preLoaderRoute: typeof AuthenticatedSchoolSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/school-admins': {
      id: '/_authenticated/school-admins'
      path: '/school-admins'
      fullPath: '/school-admins'
      preLoaderRoute: typeof AuthenticatedSchoolAdminsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/routes': {
      id: '/_authenticated/routes'
      path: '/routes'
      fullPath: '/routes'
      preLoaderRoute: typeof AuthenticatedRoutesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/reports': {
      id: '/_authenticated/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof AuthenticatedReportsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/plans': {
      id: '/_authenticated/plans'
      path: '/plans'
      fullPath: '/plans'
      preLoaderRoute: typeof AuthenticatedPlansRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/parents': {
      id: '/_authenticated/parents'
      path: '/parents'
      fullPath: '/parents'
      preLoaderRoute: typeof AuthenticatedParentsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/notifications': {
      id: '/_authenticated/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof AuthenticatedNotificationsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/my-children': {
      id: '/_authenticated/my-children'
      path: '/my-children'
      fullPath: '/my-children'
      preLoaderRoute: typeof AuthenticatedMyChildrenRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/drivers': {
      id: '/_authenticated/drivers'
      path: '/drivers'
      fullPath: '/drivers'
      preLoaderRoute: typeof AuthenticatedDriversRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/students/': {
      id: '/_authenticated/students/'
      path: '/'
      fullPath: '/students/'
      preLoaderRoute: typeof AuthenticatedStudentsIndexRouteImport
      parentRoute: typeof AuthenticatedStudentsRoute
    }
    '/_authenticated/schools/': {
      id: '/_authenticated/schools/'
      path: '/'
      fullPath: '/schools/'
      preLoaderRoute: typeof AuthenticatedSchoolsIndexRouteImport
      parentRoute: typeof AuthenticatedSchoolsRoute
    }
    '/_authenticated/drivers/': {
      id: '/_authenticated/drivers/'
      path: '/'
      fullPath: '/drivers/'
      preLoaderRoute: typeof AuthenticatedDriversIndexRouteImport
      parentRoute: typeof AuthenticatedDriversRoute
    }
    '/_authenticated/students/$studentId': {
      id: '/_authenticated/students/$studentId'
      path: '/$studentId'
      fullPath: '/students/$studentId'
      preLoaderRoute: typeof AuthenticatedStudentsStudentIdRouteImport
      parentRoute: typeof AuthenticatedStudentsRoute
    }
    '/_authenticated/schools/$schoolId': {
      id: '/_authenticated/schools/$schoolId'
      path: '/$schoolId'
      fullPath: '/schools/$schoolId'
      preLoaderRoute: typeof AuthenticatedSchoolsSchoolIdRouteImport
      parentRoute: typeof AuthenticatedSchoolsRoute
    }
  }
}

interface AuthenticatedDriversRouteChildren {
  AuthenticatedDriversIndexRoute: typeof AuthenticatedDriversIndexRoute
}

const AuthenticatedDriversRouteChildren: AuthenticatedDriversRouteChildren = {
  AuthenticatedDriversIndexRoute: AuthenticatedDriversIndexRoute,
}

const AuthenticatedDriversRouteWithChildren =
  AuthenticatedDriversRoute._addFileChildren(AuthenticatedDriversRouteChildren)

interface AuthenticatedSchoolsRouteChildren {
  AuthenticatedSchoolsSchoolIdRoute: typeof AuthenticatedSchoolsSchoolIdRoute
  AuthenticatedSchoolsIndexRoute: typeof AuthenticatedSchoolsIndexRoute
}

const AuthenticatedSchoolsRouteChildren: AuthenticatedSchoolsRouteChildren = {
  AuthenticatedSchoolsSchoolIdRoute: AuthenticatedSchoolsSchoolIdRoute,
  AuthenticatedSchoolsIndexRoute: AuthenticatedSchoolsIndexRoute,
}

const AuthenticatedSchoolsRouteWithChildren =
  AuthenticatedSchoolsRoute._addFileChildren(AuthenticatedSchoolsRouteChildren)

interface AuthenticatedStudentsRouteChildren {
  AuthenticatedStudentsStudentIdRoute: typeof AuthenticatedStudentsStudentIdRoute
  AuthenticatedStudentsIndexRoute: typeof AuthenticatedStudentsIndexRoute
}

const AuthenticatedStudentsRouteChildren: AuthenticatedStudentsRouteChildren = {
  AuthenticatedStudentsStudentIdRoute: AuthenticatedStudentsStudentIdRoute,
  AuthenticatedStudentsIndexRoute: AuthenticatedStudentsIndexRoute,
}

const AuthenticatedStudentsRouteWithChildren =
  AuthenticatedStudentsRoute._addFileChildren(
    AuthenticatedStudentsRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedDriversRoute: typeof AuthenticatedDriversRouteWithChildren
  AuthenticatedMyChildrenRoute: typeof AuthenticatedMyChildrenRoute
  AuthenticatedNotificationsRoute: typeof AuthenticatedNotificationsRoute
  AuthenticatedParentsRoute: typeof AuthenticatedParentsRoute
  AuthenticatedPlansRoute: typeof AuthenticatedPlansRoute
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
  AuthenticatedReportsRoute: typeof AuthenticatedReportsRoute
  AuthenticatedRoutesRoute: typeof AuthenticatedRoutesRoute
  AuthenticatedSchoolAdminsRoute: typeof AuthenticatedSchoolAdminsRoute
  AuthenticatedSchoolSettingsRoute: typeof AuthenticatedSchoolSettingsRoute
  AuthenticatedSchoolsRoute: typeof AuthenticatedSchoolsRouteWithChildren
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedStudentsRoute: typeof AuthenticatedStudentsRouteWithChildren
  AuthenticatedSubscriptionsRoute: typeof AuthenticatedSubscriptionsRoute
  AuthenticatedTripsRoute: typeof AuthenticatedTripsRoute
  AuthenticatedVehiclesRoute: typeof AuthenticatedVehiclesRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedDriversRoute: AuthenticatedDriversRouteWithChildren,
  AuthenticatedMyChildrenRoute: AuthenticatedMyChildrenRoute,
  AuthenticatedNotificationsRoute: AuthenticatedNotificationsRoute,
  AuthenticatedParentsRoute: AuthenticatedParentsRoute,
  AuthenticatedPlansRoute: AuthenticatedPlansRoute,
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
  AuthenticatedReportsRoute: AuthenticatedReportsRoute,
  AuthenticatedRoutesRoute: AuthenticatedRoutesRoute,
  AuthenticatedSchoolAdminsRoute: AuthenticatedSchoolAdminsRoute,
  AuthenticatedSchoolSettingsRoute: AuthenticatedSchoolSettingsRoute,
  AuthenticatedSchoolsRoute: AuthenticatedSchoolsRouteWithChildren,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedStudentsRoute: AuthenticatedStudentsRouteWithChildren,
  AuthenticatedSubscriptionsRoute: AuthenticatedSubscriptionsRoute,
  AuthenticatedTripsRoute: AuthenticatedTripsRoute,
  AuthenticatedVehiclesRoute: AuthenticatedVehiclesRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ResetPasswordRoute: ResetPasswordRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
