/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedVehiclesRouteImport } from './routes/_authenticated/vehicles'
import { Route as AuthenticatedTripsRouteImport } from './routes/_authenticated/trips'
import { Route as AuthenticatedSubscriptionsRouteImport } from './routes/_authenticated/subscriptions'
import { Route as AuthenticatedStudentsRouteImport } from './routes/_authenticated/students'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedSchoolsRouteImport } from './routes/_authenticated/schools'
import { Route as AuthenticatedSchoolSettingsRouteImport } from './routes/_authenticated/school-settings'
import { Route as AuthenticatedSchoolAdminsRouteImport } from './routes/_authenticated/school-admins'
import { Route as AuthenticatedRoutesRouteImport } from './routes/_authenticated/routes'
import { Route as AuthenticatedReportsRouteImport } from './routes/_authenticated/reports'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated/profile'
import { Route as AuthenticatedPlansRouteImport } from './routes/_authenticated/plans'
import { Route as AuthenticatedParentsRouteImport } from './routes/_authenticated/parents'
import { Route as AuthenticatedParentRouteImport } from './routes/_authenticated/parent'
import { Route as AuthenticatedNotificationsRouteImport } from './routes/_authenticated/notifications'
import { Route as AuthenticatedMyChildrenRouteImport } from './routes/_authenticated/my-children'
import { Route as AuthenticatedDriversRouteImport } from './routes/_authenticated/drivers'
import { Route as AuthenticatedDriverRouteImport } from './routes/_authenticated/driver'
import { Route as AuthenticatedDevDocsRouteImport } from './routes/_authenticated/dev-docs'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedVehiclesIndexRouteImport } from './routes/_authenticated/vehicles.index'
import { Route as AuthenticatedTripsIndexRouteImport } from './routes/_authenticated/trips.index'
import { Route as AuthenticatedStudentsIndexRouteImport } from './routes/_authenticated/students.index'
import { Route as AuthenticatedSchoolsIndexRouteImport } from './routes/_authenticated/schools.index'
import { Route as AuthenticatedRoutesIndexRouteImport } from './routes/_authenticated/routes.index'
import { Route as AuthenticatedDriversIndexRouteImport } from './routes/_authenticated/drivers.index'
import { Route as AuthenticatedVehiclesVehicleIdRouteImport } from './routes/_authenticated/vehicles.$vehicleId'
import { Route as AuthenticatedTripsTripIdRouteImport } from './routes/_authenticated/trips.$tripId'
import { Route as AuthenticatedStudentsStudentIdRouteImport } from './routes/_authenticated/students.$studentId'
import { Route as AuthenticatedSchoolsSchoolIdRouteImport } from './routes/_authenticated/schools.$schoolId'
import { Route as AuthenticatedRoutesRouteIdRouteImport } from './routes/_authenticated/routes.$routeId'
import { Route as AuthenticatedParentLiveRouteImport } from './routes/_authenticated/parent.live'
import { Route as AuthenticatedParentHistoryRouteImport } from './routes/_authenticated/parent.history'
import { Route as AuthenticatedParentDashboardRouteImport } from './routes/_authenticated/parent.dashboard'
import { Route as AuthenticatedParentChildRouteImport } from './routes/_authenticated/parent.child'
import { Route as AuthenticatedDriversDriverIdRouteImport } from './routes/_authenticated/drivers.$driverId'
import { Route as AuthenticatedDriverTodayRouteImport } from './routes/_authenticated/driver.today'
import { Route as AuthenticatedDriverStudentsRouteImport } from './routes/_authenticated/driver.students'
import { Route as AuthenticatedDriverQrRouteImport } from './routes/_authenticated/driver.qr'
import { Route as AuthenticatedDriverNavigationRouteImport } from './routes/_authenticated/driver.navigation'
import { Route as AuthenticatedDriverHistoryRouteImport } from './routes/_authenticated/driver.history'
import { Route as AuthenticatedDriverDashboardRouteImport } from './routes/_authenticated/driver.dashboard'
import { Route as AuthenticatedDriverTripTripIdRouteImport } from './routes/_authenticated/driver.trip.$tripId'

const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedVehiclesRoute = AuthenticatedVehiclesRouteImport.update({
  id: '/vehicles',
  path: '/vehicles',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTripsRoute = AuthenticatedTripsRouteImport.update({
  id: '/trips',
  path: '/trips',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSubscriptionsRoute =
  AuthenticatedSubscriptionsRouteImport.update({
    id: '/subscriptions',
    path: '/subscriptions',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedStudentsRoute = AuthenticatedStudentsRouteImport.update({
  id: '/students',
  path: '/students',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSchoolsRoute = AuthenticatedSchoolsRouteImport.update({
  id: '/schools',
  path: '/schools',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSchoolSettingsRoute =
  AuthenticatedSchoolSettingsRouteImport.update({
    id: '/school-settings',
    path: '/school-settings',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSchoolAdminsRoute =
  AuthenticatedSchoolAdminsRouteImport.update({
    id: '/school-admins',
    path: '/school-admins',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedRoutesRoute = AuthenticatedRoutesRouteImport.update({
  id: '/routes',
  path: '/routes',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedReportsRoute = AuthenticatedReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPlansRoute = AuthenticatedPlansRouteImport.update({
  id: '/plans',
  path: '/plans',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedParentsRoute = AuthenticatedParentsRouteImport.update({
  id: '/parents',
  path: '/parents',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedParentRoute = AuthenticatedParentRouteImport.update({
  id: '/parent',
  path: '/parent',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedNotificationsRoute =
  AuthenticatedNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMyChildrenRoute = AuthenticatedMyChildrenRouteImport.update({
  id: '/my-children',
  path: '/my-children',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDriversRoute = AuthenticatedDriversRouteImport.update({
  id: '/drivers',
  path: '/drivers',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDriverRoute = AuthenticatedDriverRouteImport.update({
  id: '/driver',
  path: '/driver',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDevDocsRoute = AuthenticatedDevDocsRouteImport.update({
  id: '/dev-docs',
  path: '/dev-docs',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedVehiclesIndexRoute =
  AuthenticatedVehiclesIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedVehiclesRoute,
  } as any)
const AuthenticatedTripsIndexRoute = AuthenticatedTripsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedTripsRoute,
} as any)
const AuthenticatedStudentsIndexRoute =
  AuthenticatedStudentsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedStudentsRoute,
  } as any)
const AuthenticatedSchoolsIndexRoute =
  AuthenticatedSchoolsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedSchoolsRoute,
  } as any)
const AuthenticatedRoutesIndexRoute =
  AuthenticatedRoutesIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedRoutesRoute,
  } as any)
const AuthenticatedDriversIndexRoute =
  AuthenticatedDriversIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedDriversRoute,
  } as any)
const AuthenticatedVehiclesVehicleIdRoute =
  AuthenticatedVehiclesVehicleIdRouteImport.update({
    id: '/$vehicleId',
    path: '/$vehicleId',
    getParentRoute: () => AuthenticatedVehiclesRoute,
  } as any)
const AuthenticatedTripsTripIdRoute =
  AuthenticatedTripsTripIdRouteImport.update({
    id: '/$tripId',
    path: '/$tripId',
    getParentRoute: () => AuthenticatedTripsRoute,
  } as any)
const AuthenticatedStudentsStudentIdRoute =
  AuthenticatedStudentsStudentIdRouteImport.update({
    id: '/$studentId',
    path: '/$studentId',
    getParentRoute: () => AuthenticatedStudentsRoute,
  } as any)
const AuthenticatedSchoolsSchoolIdRoute =
  AuthenticatedSchoolsSchoolIdRouteImport.update({
    id: '/$schoolId',
    path: '/$schoolId',
    getParentRoute: () => AuthenticatedSchoolsRoute,
  } as any)
const AuthenticatedRoutesRouteIdRoute =
  AuthenticatedRoutesRouteIdRouteImport.update({
    id: '/$routeId',
    path: '/$routeId',
    getParentRoute: () => AuthenticatedRoutesRoute,
  } as any)
const AuthenticatedParentLiveRoute = AuthenticatedParentLiveRouteImport.update({
  id: '/live',
  path: '/live',
  getParentRoute: () => AuthenticatedParentRoute,
} as any)
const AuthenticatedParentHistoryRoute =
  AuthenticatedParentHistoryRouteImport.update({
    id: '/history',
    path: '/history',
    getParentRoute: () => AuthenticatedParentRoute,
  } as any)
const AuthenticatedParentDashboardRoute =
  AuthenticatedParentDashboardRouteImport.update({
    id: '/dashboard',
    path: '/dashboard',
    getParentRoute: () => AuthenticatedParentRoute,
  } as any)
const AuthenticatedParentChildRoute =
  AuthenticatedParentChildRouteImport.update({
    id: '/child',
    path: '/child',
    getParentRoute: () => AuthenticatedParentRoute,
  } as any)
const AuthenticatedDriversDriverIdRoute =
  AuthenticatedDriversDriverIdRouteImport.update({
    id: '/$driverId',
    path: '/$driverId',
    getParentRoute: () => AuthenticatedDriversRoute,
  } as any)
const AuthenticatedDriverTodayRoute =
  AuthenticatedDriverTodayRouteImport.update({
    id: '/today',
    path: '/today',
    getParentRoute: () => AuthenticatedDriverRoute,
  } as any)
const AuthenticatedDriverStudentsRoute =
  AuthenticatedDriverStudentsRouteImport.update({
    id: '/students',
    path: '/students',
    getParentRoute: () => AuthenticatedDriverRoute,
  } as any)
const AuthenticatedDriverQrRoute = AuthenticatedDriverQrRouteImport.update({
  id: '/qr',
  path: '/qr',
  getParentRoute: () => AuthenticatedDriverRoute,
} as any)
const AuthenticatedDriverNavigationRoute =
  AuthenticatedDriverNavigationRouteImport.update({
    id: '/navigation',
    path: '/navigation',
    getParentRoute: () => AuthenticatedDriverRoute,
  } as any)
const AuthenticatedDriverHistoryRoute =
  AuthenticatedDriverHistoryRouteImport.update({
    id: '/history',
    path: '/history',
    getParentRoute: () => AuthenticatedDriverRoute,
  } as any)
const AuthenticatedDriverDashboardRoute =
  AuthenticatedDriverDashboardRouteImport.update({
    id: '/dashboard',
    path: '/dashboard',
    getParentRoute: () => AuthenticatedDriverRoute,
  } as any)
const AuthenticatedDriverTripTripIdRoute =
  AuthenticatedDriverTripTripIdRouteImport.update({
    id: '/trip/$tripId',
    path: '/trip/$tripId',
    getParentRoute: () => AuthenticatedDriverRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/dev-docs': typeof AuthenticatedDevDocsRoute
  '/driver': typeof AuthenticatedDriverRouteWithChildren
  '/drivers': typeof AuthenticatedDriversRouteWithChildren
  '/my-children': typeof AuthenticatedMyChildrenRoute
  '/notifications': typeof AuthenticatedNotificationsRoute
  '/parent': typeof AuthenticatedParentRouteWithChildren
  '/parents': typeof AuthenticatedParentsRoute
  '/plans': typeof AuthenticatedPlansRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/reports': typeof AuthenticatedReportsRoute
  '/routes': typeof AuthenticatedRoutesRouteWithChildren
  '/school-admins': typeof AuthenticatedSchoolAdminsRoute
  '/school-settings': typeof AuthenticatedSchoolSettingsRoute
  '/schools': typeof AuthenticatedSchoolsRouteWithChildren
  '/settings': typeof AuthenticatedSettingsRoute
  '/students': typeof AuthenticatedStudentsRouteWithChildren
  '/subscriptions': typeof AuthenticatedSubscriptionsRoute
  '/trips': typeof AuthenticatedTripsRouteWithChildren
  '/vehicles': typeof AuthenticatedVehiclesRouteWithChildren
  '/driver/dashboard': typeof AuthenticatedDriverDashboardRoute
  '/driver/history': typeof AuthenticatedDriverHistoryRoute
  '/driver/navigation': typeof AuthenticatedDriverNavigationRoute
  '/driver/qr': typeof AuthenticatedDriverQrRoute
  '/driver/students': typeof AuthenticatedDriverStudentsRoute
  '/driver/today': typeof AuthenticatedDriverTodayRoute
  '/drivers/$driverId': typeof AuthenticatedDriversDriverIdRoute
  '/parent/child': typeof AuthenticatedParentChildRoute
  '/parent/dashboard': typeof AuthenticatedParentDashboardRoute
  '/parent/history': typeof AuthenticatedParentHistoryRoute
  '/parent/live': typeof AuthenticatedParentLiveRoute
  '/routes/$routeId': typeof AuthenticatedRoutesRouteIdRoute
  '/schools/$schoolId': typeof AuthenticatedSchoolsSchoolIdRoute
  '/students/$studentId': typeof AuthenticatedStudentsStudentIdRoute
  '/trips/$tripId': typeof AuthenticatedTripsTripIdRoute
  '/vehicles/$vehicleId': typeof AuthenticatedVehiclesVehicleIdRoute
  '/drivers/': typeof AuthenticatedDriversIndexRoute
  '/routes/': typeof AuthenticatedRoutesIndexRoute
  '/schools/': typeof AuthenticatedSchoolsIndexRoute
  '/students/': typeof AuthenticatedStudentsIndexRoute
  '/trips/': typeof AuthenticatedTripsIndexRoute
  '/vehicles/': typeof AuthenticatedVehiclesIndexRoute
  '/driver/trip/$tripId': typeof AuthenticatedDriverTripTripIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/dev-docs': typeof AuthenticatedDevDocsRoute
  '/driver': typeof AuthenticatedDriverRouteWithChildren
  '/my-children': typeof AuthenticatedMyChildrenRoute
  '/notifications': typeof AuthenticatedNotificationsRoute
  '/parent': typeof AuthenticatedParentRouteWithChildren
  '/parents': typeof AuthenticatedParentsRoute
  '/plans': typeof AuthenticatedPlansRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/reports': typeof AuthenticatedReportsRoute
  '/school-admins': typeof AuthenticatedSchoolAdminsRoute
  '/school-settings': typeof AuthenticatedSchoolSettingsRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/subscriptions': typeof AuthenticatedSubscriptionsRoute
  '/driver/dashboard': typeof AuthenticatedDriverDashboardRoute
  '/driver/history': typeof AuthenticatedDriverHistoryRoute
  '/driver/navigation': typeof AuthenticatedDriverNavigationRoute
  '/driver/qr': typeof AuthenticatedDriverQrRoute
  '/driver/students': typeof AuthenticatedDriverStudentsRoute
  '/driver/today': typeof AuthenticatedDriverTodayRoute
  '/drivers/$driverId': typeof AuthenticatedDriversDriverIdRoute
  '/parent/child': typeof AuthenticatedParentChildRoute
  '/parent/dashboard': typeof AuthenticatedParentDashboardRoute
  '/parent/history': typeof AuthenticatedParentHistoryRoute
  '/parent/live': typeof AuthenticatedParentLiveRoute
  '/routes/$routeId': typeof AuthenticatedRoutesRouteIdRoute
  '/schools/$schoolId': typeof AuthenticatedSchoolsSchoolIdRoute
  '/students/$studentId': typeof AuthenticatedStudentsStudentIdRoute
  '/trips/$tripId': typeof AuthenticatedTripsTripIdRoute
  '/vehicles/$vehicleId': typeof AuthenticatedVehiclesVehicleIdRoute
  '/drivers': typeof AuthenticatedDriversIndexRoute
  '/routes': typeof AuthenticatedRoutesIndexRoute
  '/schools': typeof AuthenticatedSchoolsIndexRoute
  '/students': typeof AuthenticatedStudentsIndexRoute
  '/trips': typeof AuthenticatedTripsIndexRoute
  '/vehicles': typeof AuthenticatedVehiclesIndexRoute
  '/driver/trip/$tripId': typeof AuthenticatedDriverTripTripIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/dev-docs': typeof AuthenticatedDevDocsRoute
  '/_authenticated/driver': typeof AuthenticatedDriverRouteWithChildren
  '/_authenticated/drivers': typeof AuthenticatedDriversRouteWithChildren
  '/_authenticated/my-children': typeof AuthenticatedMyChildrenRoute
  '/_authenticated/notifications': typeof AuthenticatedNotificationsRoute
  '/_authenticated/parent': typeof AuthenticatedParentRouteWithChildren
  '/_authenticated/parents': typeof AuthenticatedParentsRoute
  '/_authenticated/plans': typeof AuthenticatedPlansRoute
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/_authenticated/reports': typeof AuthenticatedReportsRoute
  '/_authenticated/routes': typeof AuthenticatedRoutesRouteWithChildren
  '/_authenticated/school-admins': typeof AuthenticatedSchoolAdminsRoute
  '/_authenticated/school-settings': typeof AuthenticatedSchoolSettingsRoute
  '/_authenticated/schools': typeof AuthenticatedSchoolsRouteWithChildren
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/students': typeof AuthenticatedStudentsRouteWithChildren
  '/_authenticated/subscriptions': typeof AuthenticatedSubscriptionsRoute
  '/_authenticated/trips': typeof AuthenticatedTripsRouteWithChildren
  '/_authenticated/vehicles': typeof AuthenticatedVehiclesRouteWithChildren
  '/_authenticated/driver/dashboard': typeof AuthenticatedDriverDashboardRoute
  '/_authenticated/driver/history': typeof AuthenticatedDriverHistoryRoute
  '/_authenticated/driver/navigation': typeof AuthenticatedDriverNavigationRoute
  '/_authenticated/driver/qr': typeof AuthenticatedDriverQrRoute
  '/_authenticated/driver/students': typeof AuthenticatedDriverStudentsRoute
  '/_authenticated/driver/today': typeof AuthenticatedDriverTodayRoute
  '/_authenticated/drivers/$driverId': typeof AuthenticatedDriversDriverIdRoute
  '/_authenticated/parent/child': typeof AuthenticatedParentChildRoute
  '/_authenticated/parent/dashboard': typeof AuthenticatedParentDashboardRoute
  '/_authenticated/parent/history': typeof AuthenticatedParentHistoryRoute
  '/_authenticated/parent/live': typeof AuthenticatedParentLiveRoute
  '/_authenticated/routes/$routeId': typeof AuthenticatedRoutesRouteIdRoute
  '/_authenticated/schools/$schoolId': typeof AuthenticatedSchoolsSchoolIdRoute
  '/_authenticated/students/$studentId': typeof AuthenticatedStudentsStudentIdRoute
  '/_authenticated/trips/$tripId': typeof AuthenticatedTripsTripIdRoute
  '/_authenticated/vehicles/$vehicleId': typeof AuthenticatedVehiclesVehicleIdRoute
  '/_authenticated/drivers/': typeof AuthenticatedDriversIndexRoute
  '/_authenticated/routes/': typeof AuthenticatedRoutesIndexRoute
  '/_authenticated/schools/': typeof AuthenticatedSchoolsIndexRoute
  '/_authenticated/students/': typeof AuthenticatedStudentsIndexRoute
  '/_authenticated/trips/': typeof AuthenticatedTripsIndexRoute
  '/_authenticated/vehicles/': typeof AuthenticatedVehiclesIndexRoute
  '/_authenticated/driver/trip/$tripId': typeof AuthenticatedDriverTripTripIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/reset-password'
    | '/dashboard'
    | '/dev-docs'
    | '/driver'
    | '/drivers'
    | '/my-children'
    | '/notifications'
    | '/parent'
    | '/parents'
    | '/plans'
    | '/profile'
    | '/reports'
    | '/routes'
    | '/school-admins'
    | '/school-settings'
    | '/schools'
    | '/settings'
    | '/students'
    | '/subscriptions'
    | '/trips'
    | '/vehicles'
    | '/driver/dashboard'
    | '/driver/history'
    | '/driver/navigation'
    | '/driver/qr'
    | '/driver/students'
    | '/driver/today'
    | '/drivers/$driverId'
    | '/parent/child'
    | '/parent/dashboard'
    | '/parent/history'
    | '/parent/live'
    | '/routes/$routeId'
    | '/schools/$schoolId'
    | '/students/$studentId'
    | '/trips/$tripId'
    | '/vehicles/$vehicleId'
    | '/drivers/'
    | '/routes/'
    | '/schools/'
    | '/students/'
    | '/trips/'
    | '/vehicles/'
    | '/driver/trip/$tripId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/reset-password'
    | '/dashboard'
    | '/dev-docs'
    | '/driver'
    | '/my-children'
    | '/notifications'
    | '/parent'
    | '/parents'
    | '/plans'
    | '/profile'
    | '/reports'
    | '/school-admins'
    | '/school-settings'
    | '/settings'
    | '/subscriptions'
    | '/driver/dashboard'
    | '/driver/history'
    | '/driver/navigation'
    | '/driver/qr'
    | '/driver/students'
    | '/driver/today'
    | '/drivers/$driverId'
    | '/parent/child'
    | '/parent/dashboard'
    | '/parent/history'
    | '/parent/live'
    | '/routes/$routeId'
    | '/schools/$schoolId'
    | '/students/$studentId'
    | '/trips/$tripId'
    | '/vehicles/$vehicleId'
    | '/drivers'
    | '/routes'
    | '/schools'
    | '/students'
    | '/trips'
    | '/vehicles'
    | '/driver/trip/$tripId'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/reset-password'
    | '/_authenticated/dashboard'
    | '/_authenticated/dev-docs'
    | '/_authenticated/driver'
    | '/_authenticated/drivers'
    | '/_authenticated/my-children'
    | '/_authenticated/notifications'
    | '/_authenticated/parent'
    | '/_authenticated/parents'
    | '/_authenticated/plans'
    | '/_authenticated/profile'
    | '/_authenticated/reports'
    | '/_authenticated/routes'
    | '/_authenticated/school-admins'
    | '/_authenticated/school-settings'
    | '/_authenticated/schools'
    | '/_authenticated/settings'
    | '/_authenticated/students'
    | '/_authenticated/subscriptions'
    | '/_authenticated/trips'
    | '/_authenticated/vehicles'
    | '/_authenticated/driver/dashboard'
    | '/_authenticated/driver/history'
    | '/_authenticated/driver/navigation'
    | '/_authenticated/driver/qr'
    | '/_authenticated/driver/students'
    | '/_authenticated/driver/today'
    | '/_authenticated/drivers/$driverId'
    | '/_authenticated/parent/child'
    | '/_authenticated/parent/dashboard'
    | '/_authenticated/parent/history'
    | '/_authenticated/parent/live'
    | '/_authenticated/routes/$routeId'
    | '/_authenticated/schools/$schoolId'
    | '/_authenticated/students/$studentId'
    | '/_authenticated/trips/$tripId'
    | '/_authenticated/vehicles/$vehicleId'
    | '/_authenticated/drivers/'
    | '/_authenticated/routes/'
    | '/_authenticated/schools/'
    | '/_authenticated/students/'
    | '/_authenticated/trips/'
    | '/_authenticated/vehicles/'
    | '/_authenticated/driver/trip/$tripId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/vehicles': {
      id: '/_authenticated/vehicles'
      path: '/vehicles'
      fullPath: '/vehicles'
      preLoaderRoute: typeof AuthenticatedVehiclesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/trips': {
      id: '/_authenticated/trips'
      path: '/trips'
      fullPath: '/trips'
      preLoaderRoute: typeof AuthenticatedTripsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/subscriptions': {
      id: '/_authenticated/subscriptions'
      path: '/subscriptions'
      fullPath: '/subscriptions'
      preLoaderRoute: typeof AuthenticatedSubscriptionsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/students': {
      id: '/_authenticated/students'
      path: '/students'
      fullPath: '/students'
      preLoaderRoute: typeof AuthenticatedStudentsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/schools': {
      id: '/_authenticated/schools'
      path: '/schools'
      fullPath: '/schools'
      preLoaderRoute: typeof AuthenticatedSchoolsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/school-settings': {
      id: '/_authenticated/school-settings'
      path: '/school-settings'
      fullPath: '/school-settings'
      preLoaderRoute: typeof AuthenticatedSchoolSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/school-admins': {
      id: '/_authenticated/school-admins'
      path: '/school-admins'
      fullPath: '/school-admins'
      preLoaderRoute: typeof AuthenticatedSchoolAdminsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/routes': {
      id: '/_authenticated/routes'
      path: '/routes'
      fullPath: '/routes'
      preLoaderRoute: typeof AuthenticatedRoutesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/reports': {
      id: '/_authenticated/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof AuthenticatedReportsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/plans': {
      id: '/_authenticated/plans'
      path: '/plans'
      fullPath: '/plans'
      preLoaderRoute: typeof AuthenticatedPlansRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/parents': {
      id: '/_authenticated/parents'
      path: '/parents'
      fullPath: '/parents'
      preLoaderRoute: typeof AuthenticatedParentsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/parent': {
      id: '/_authenticated/parent'
      path: '/parent'
      fullPath: '/parent'
      preLoaderRoute: typeof AuthenticatedParentRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/notifications': {
      id: '/_authenticated/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof AuthenticatedNotificationsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/my-children': {
      id: '/_authenticated/my-children'
      path: '/my-children'
      fullPath: '/my-children'
      preLoaderRoute: typeof AuthenticatedMyChildrenRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/drivers': {
      id: '/_authenticated/drivers'
      path: '/drivers'
      fullPath: '/drivers'
      preLoaderRoute: typeof AuthenticatedDriversRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/driver': {
      id: '/_authenticated/driver'
      path: '/driver'
      fullPath: '/driver'
      preLoaderRoute: typeof AuthenticatedDriverRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dev-docs': {
      id: '/_authenticated/dev-docs'
      path: '/dev-docs'
      fullPath: '/dev-docs'
      preLoaderRoute: typeof AuthenticatedDevDocsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/vehicles/': {
      id: '/_authenticated/vehicles/'
      path: '/'
      fullPath: '/vehicles/'
      preLoaderRoute: typeof AuthenticatedVehiclesIndexRouteImport
      parentRoute: typeof AuthenticatedVehiclesRoute
    }
    '/_authenticated/trips/': {
      id: '/_authenticated/trips/'
      path: '/'
      fullPath: '/trips/'
      preLoaderRoute: typeof AuthenticatedTripsIndexRouteImport
      parentRoute: typeof AuthenticatedTripsRoute
    }
    '/_authenticated/students/': {
      id: '/_authenticated/students/'
      path: '/'
      fullPath: '/students/'
      preLoaderRoute: typeof AuthenticatedStudentsIndexRouteImport
      parentRoute: typeof AuthenticatedStudentsRoute
    }
    '/_authenticated/schools/': {
      id: '/_authenticated/schools/'
      path: '/'
      fullPath: '/schools/'
      preLoaderRoute: typeof AuthenticatedSchoolsIndexRouteImport
      parentRoute: typeof AuthenticatedSchoolsRoute
    }
    '/_authenticated/routes/': {
      id: '/_authenticated/routes/'
      path: '/'
      fullPath: '/routes/'
      preLoaderRoute: typeof AuthenticatedRoutesIndexRouteImport
      parentRoute: typeof AuthenticatedRoutesRoute
    }
    '/_authenticated/drivers/': {
      id: '/_authenticated/drivers/'
      path: '/'
      fullPath: '/drivers/'
      preLoaderRoute: typeof AuthenticatedDriversIndexRouteImport
      parentRoute: typeof AuthenticatedDriversRoute
    }
    '/_authenticated/vehicles/$vehicleId': {
      id: '/_authenticated/vehicles/$vehicleId'
      path: '/$vehicleId'
      fullPath: '/vehicles/$vehicleId'
      preLoaderRoute: typeof AuthenticatedVehiclesVehicleIdRouteImport
      parentRoute: typeof AuthenticatedVehiclesRoute
    }
    '/_authenticated/trips/$tripId': {
      id: '/_authenticated/trips/$tripId'
      path: '/$tripId'
      fullPath: '/trips/$tripId'
      preLoaderRoute: typeof AuthenticatedTripsTripIdRouteImport
      parentRoute: typeof AuthenticatedTripsRoute
    }
    '/_authenticated/students/$studentId': {
      id: '/_authenticated/students/$studentId'
      path: '/$studentId'
      fullPath: '/students/$studentId'
      preLoaderRoute: typeof AuthenticatedStudentsStudentIdRouteImport
      parentRoute: typeof AuthenticatedStudentsRoute
    }
    '/_authenticated/schools/$schoolId': {
      id: '/_authenticated/schools/$schoolId'
      path: '/$schoolId'
      fullPath: '/schools/$schoolId'
      preLoaderRoute: typeof AuthenticatedSchoolsSchoolIdRouteImport
      parentRoute: typeof AuthenticatedSchoolsRoute
    }
    '/_authenticated/routes/$routeId': {
      id: '/_authenticated/routes/$routeId'
      path: '/$routeId'
      fullPath: '/routes/$routeId'
      preLoaderRoute: typeof AuthenticatedRoutesRouteIdRouteImport
      parentRoute: typeof AuthenticatedRoutesRoute
    }
    '/_authenticated/parent/live': {
      id: '/_authenticated/parent/live'
      path: '/live'
      fullPath: '/parent/live'
      preLoaderRoute: typeof AuthenticatedParentLiveRouteImport
      parentRoute: typeof AuthenticatedParentRoute
    }
    '/_authenticated/parent/history': {
      id: '/_authenticated/parent/history'
      path: '/history'
      fullPath: '/parent/history'
      preLoaderRoute: typeof AuthenticatedParentHistoryRouteImport
      parentRoute: typeof AuthenticatedParentRoute
    }
    '/_authenticated/parent/dashboard': {
      id: '/_authenticated/parent/dashboard'
      path: '/dashboard'
      fullPath: '/parent/dashboard'
      preLoaderRoute: typeof AuthenticatedParentDashboardRouteImport
      parentRoute: typeof AuthenticatedParentRoute
    }
    '/_authenticated/parent/child': {
      id: '/_authenticated/parent/child'
      path: '/child'
      fullPath: '/parent/child'
      preLoaderRoute: typeof AuthenticatedParentChildRouteImport
      parentRoute: typeof AuthenticatedParentRoute
    }
    '/_authenticated/drivers/$driverId': {
      id: '/_authenticated/drivers/$driverId'
      path: '/$driverId'
      fullPath: '/drivers/$driverId'
      preLoaderRoute: typeof AuthenticatedDriversDriverIdRouteImport
      parentRoute: typeof AuthenticatedDriversRoute
    }
    '/_authenticated/driver/today': {
      id: '/_authenticated/driver/today'
      path: '/today'
      fullPath: '/driver/today'
      preLoaderRoute: typeof AuthenticatedDriverTodayRouteImport
      parentRoute: typeof AuthenticatedDriverRoute
    }
    '/_authenticated/driver/students': {
      id: '/_authenticated/driver/students'
      path: '/students'
      fullPath: '/driver/students'
      preLoaderRoute: typeof AuthenticatedDriverStudentsRouteImport
      parentRoute: typeof AuthenticatedDriverRoute
    }
    '/_authenticated/driver/qr': {
      id: '/_authenticated/driver/qr'
      path: '/qr'
      fullPath: '/driver/qr'
      preLoaderRoute: typeof AuthenticatedDriverQrRouteImport
      parentRoute: typeof AuthenticatedDriverRoute
    }
    '/_authenticated/driver/navigation': {
      id: '/_authenticated/driver/navigation'
      path: '/navigation'
      fullPath: '/driver/navigation'
      preLoaderRoute: typeof AuthenticatedDriverNavigationRouteImport
      parentRoute: typeof AuthenticatedDriverRoute
    }
    '/_authenticated/driver/history': {
      id: '/_authenticated/driver/history'
      path: '/history'
      fullPath: '/driver/history'
      preLoaderRoute: typeof AuthenticatedDriverHistoryRouteImport
      parentRoute: typeof AuthenticatedDriverRoute
    }
    '/_authenticated/driver/dashboard': {
      id: '/_authenticated/driver/dashboard'
      path: '/dashboard'
      fullPath: '/driver/dashboard'
      preLoaderRoute: typeof AuthenticatedDriverDashboardRouteImport
      parentRoute: typeof AuthenticatedDriverRoute
    }
    '/_authenticated/driver/trip/$tripId': {
      id: '/_authenticated/driver/trip/$tripId'
      path: '/trip/$tripId'
      fullPath: '/driver/trip/$tripId'
      preLoaderRoute: typeof AuthenticatedDriverTripTripIdRouteImport
      parentRoute: typeof AuthenticatedDriverRoute
    }
  }
}

interface AuthenticatedDriverRouteChildren {
  AuthenticatedDriverDashboardRoute: typeof AuthenticatedDriverDashboardRoute
  AuthenticatedDriverHistoryRoute: typeof AuthenticatedDriverHistoryRoute
  AuthenticatedDriverNavigationRoute: typeof AuthenticatedDriverNavigationRoute
  AuthenticatedDriverQrRoute: typeof AuthenticatedDriverQrRoute
  AuthenticatedDriverStudentsRoute: typeof AuthenticatedDriverStudentsRoute
  AuthenticatedDriverTodayRoute: typeof AuthenticatedDriverTodayRoute
  AuthenticatedDriverTripTripIdRoute: typeof AuthenticatedDriverTripTripIdRoute
}

const AuthenticatedDriverRouteChildren: AuthenticatedDriverRouteChildren = {
  AuthenticatedDriverDashboardRoute: AuthenticatedDriverDashboardRoute,
  AuthenticatedDriverHistoryRoute: AuthenticatedDriverHistoryRoute,
  AuthenticatedDriverNavigationRoute: AuthenticatedDriverNavigationRoute,
  AuthenticatedDriverQrRoute: AuthenticatedDriverQrRoute,
  AuthenticatedDriverStudentsRoute: AuthenticatedDriverStudentsRoute,
  AuthenticatedDriverTodayRoute: AuthenticatedDriverTodayRoute,
  AuthenticatedDriverTripTripIdRoute: AuthenticatedDriverTripTripIdRoute,
}

const AuthenticatedDriverRouteWithChildren =
  AuthenticatedDriverRoute._addFileChildren(AuthenticatedDriverRouteChildren)

interface AuthenticatedDriversRouteChildren {
  AuthenticatedDriversDriverIdRoute: typeof AuthenticatedDriversDriverIdRoute
  AuthenticatedDriversIndexRoute: typeof AuthenticatedDriversIndexRoute
}

const AuthenticatedDriversRouteChildren: AuthenticatedDriversRouteChildren = {
  AuthenticatedDriversDriverIdRoute: AuthenticatedDriversDriverIdRoute,
  AuthenticatedDriversIndexRoute: AuthenticatedDriversIndexRoute,
}

const AuthenticatedDriversRouteWithChildren =
  AuthenticatedDriversRoute._addFileChildren(AuthenticatedDriversRouteChildren)

interface AuthenticatedParentRouteChildren {
  AuthenticatedParentChildRoute: typeof AuthenticatedParentChildRoute
  AuthenticatedParentDashboardRoute: typeof AuthenticatedParentDashboardRoute
  AuthenticatedParentHistoryRoute: typeof AuthenticatedParentHistoryRoute
  AuthenticatedParentLiveRoute: typeof AuthenticatedParentLiveRoute
}

const AuthenticatedParentRouteChildren: AuthenticatedParentRouteChildren = {
  AuthenticatedParentChildRoute: AuthenticatedParentChildRoute,
  AuthenticatedParentDashboardRoute: AuthenticatedParentDashboardRoute,
  AuthenticatedParentHistoryRoute: AuthenticatedParentHistoryRoute,
  AuthenticatedParentLiveRoute: AuthenticatedParentLiveRoute,
}

const AuthenticatedParentRouteWithChildren =
  AuthenticatedParentRoute._addFileChildren(AuthenticatedParentRouteChildren)

interface AuthenticatedRoutesRouteChildren {
  AuthenticatedRoutesRouteIdRoute: typeof AuthenticatedRoutesRouteIdRoute
  AuthenticatedRoutesIndexRoute: typeof AuthenticatedRoutesIndexRoute
}

const AuthenticatedRoutesRouteChildren: AuthenticatedRoutesRouteChildren = {
  AuthenticatedRoutesRouteIdRoute: AuthenticatedRoutesRouteIdRoute,
  AuthenticatedRoutesIndexRoute: AuthenticatedRoutesIndexRoute,
}

const AuthenticatedRoutesRouteWithChildren =
  AuthenticatedRoutesRoute._addFileChildren(AuthenticatedRoutesRouteChildren)

interface AuthenticatedSchoolsRouteChildren {
  AuthenticatedSchoolsSchoolIdRoute: typeof AuthenticatedSchoolsSchoolIdRoute
  AuthenticatedSchoolsIndexRoute: typeof AuthenticatedSchoolsIndexRoute
}

const AuthenticatedSchoolsRouteChildren: AuthenticatedSchoolsRouteChildren = {
  AuthenticatedSchoolsSchoolIdRoute: AuthenticatedSchoolsSchoolIdRoute,
  AuthenticatedSchoolsIndexRoute: AuthenticatedSchoolsIndexRoute,
}

const AuthenticatedSchoolsRouteWithChildren =
  AuthenticatedSchoolsRoute._addFileChildren(AuthenticatedSchoolsRouteChildren)

interface AuthenticatedStudentsRouteChildren {
  AuthenticatedStudentsStudentIdRoute: typeof AuthenticatedStudentsStudentIdRoute
  AuthenticatedStudentsIndexRoute: typeof AuthenticatedStudentsIndexRoute
}

const AuthenticatedStudentsRouteChildren: AuthenticatedStudentsRouteChildren = {
  AuthenticatedStudentsStudentIdRoute: AuthenticatedStudentsStudentIdRoute,
  AuthenticatedStudentsIndexRoute: AuthenticatedStudentsIndexRoute,
}

const AuthenticatedStudentsRouteWithChildren =
  AuthenticatedStudentsRoute._addFileChildren(
    AuthenticatedStudentsRouteChildren,
  )

interface AuthenticatedTripsRouteChildren {
  AuthenticatedTripsTripIdRoute: typeof AuthenticatedTripsTripIdRoute
  AuthenticatedTripsIndexRoute: typeof AuthenticatedTripsIndexRoute
}

const AuthenticatedTripsRouteChildren: AuthenticatedTripsRouteChildren = {
  AuthenticatedTripsTripIdRoute: AuthenticatedTripsTripIdRoute,
  AuthenticatedTripsIndexRoute: AuthenticatedTripsIndexRoute,
}

const AuthenticatedTripsRouteWithChildren =
  AuthenticatedTripsRoute._addFileChildren(AuthenticatedTripsRouteChildren)

interface AuthenticatedVehiclesRouteChildren {
  AuthenticatedVehiclesVehicleIdRoute: typeof AuthenticatedVehiclesVehicleIdRoute
  AuthenticatedVehiclesIndexRoute: typeof AuthenticatedVehiclesIndexRoute
}

const AuthenticatedVehiclesRouteChildren: AuthenticatedVehiclesRouteChildren = {
  AuthenticatedVehiclesVehicleIdRoute: AuthenticatedVehiclesVehicleIdRoute,
  AuthenticatedVehiclesIndexRoute: AuthenticatedVehiclesIndexRoute,
}

const AuthenticatedVehiclesRouteWithChildren =
  AuthenticatedVehiclesRoute._addFileChildren(
    AuthenticatedVehiclesRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedDevDocsRoute: typeof AuthenticatedDevDocsRoute
  AuthenticatedDriverRoute: typeof AuthenticatedDriverRouteWithChildren
  AuthenticatedDriversRoute: typeof AuthenticatedDriversRouteWithChildren
  AuthenticatedMyChildrenRoute: typeof AuthenticatedMyChildrenRoute
  AuthenticatedNotificationsRoute: typeof AuthenticatedNotificationsRoute
  AuthenticatedParentRoute: typeof AuthenticatedParentRouteWithChildren
  AuthenticatedParentsRoute: typeof AuthenticatedParentsRoute
  AuthenticatedPlansRoute: typeof AuthenticatedPlansRoute
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
  AuthenticatedReportsRoute: typeof AuthenticatedReportsRoute
  AuthenticatedRoutesRoute: typeof AuthenticatedRoutesRouteWithChildren
  AuthenticatedSchoolAdminsRoute: typeof AuthenticatedSchoolAdminsRoute
  AuthenticatedSchoolSettingsRoute: typeof AuthenticatedSchoolSettingsRoute
  AuthenticatedSchoolsRoute: typeof AuthenticatedSchoolsRouteWithChildren
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedStudentsRoute: typeof AuthenticatedStudentsRouteWithChildren
  AuthenticatedSubscriptionsRoute: typeof AuthenticatedSubscriptionsRoute
  AuthenticatedTripsRoute: typeof AuthenticatedTripsRouteWithChildren
  AuthenticatedVehiclesRoute: typeof AuthenticatedVehiclesRouteWithChildren
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedDevDocsRoute: AuthenticatedDevDocsRoute,
  AuthenticatedDriverRoute: AuthenticatedDriverRouteWithChildren,
  AuthenticatedDriversRoute: AuthenticatedDriversRouteWithChildren,
  AuthenticatedMyChildrenRoute: AuthenticatedMyChildrenRoute,
  AuthenticatedNotificationsRoute: AuthenticatedNotificationsRoute,
  AuthenticatedParentRoute: AuthenticatedParentRouteWithChildren,
  AuthenticatedParentsRoute: AuthenticatedParentsRoute,
  AuthenticatedPlansRoute: AuthenticatedPlansRoute,
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
  AuthenticatedReportsRoute: AuthenticatedReportsRoute,
  AuthenticatedRoutesRoute: AuthenticatedRoutesRouteWithChildren,
  AuthenticatedSchoolAdminsRoute: AuthenticatedSchoolAdminsRoute,
  AuthenticatedSchoolSettingsRoute: AuthenticatedSchoolSettingsRoute,
  AuthenticatedSchoolsRoute: AuthenticatedSchoolsRouteWithChildren,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedStudentsRoute: AuthenticatedStudentsRouteWithChildren,
  AuthenticatedSubscriptionsRoute: AuthenticatedSubscriptionsRoute,
  AuthenticatedTripsRoute: AuthenticatedTripsRouteWithChildren,
  AuthenticatedVehiclesRoute: AuthenticatedVehiclesRouteWithChildren,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ResetPasswordRoute: ResetPasswordRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
